### ISSUE TITLE
Kraken good accessibility - Completed

### ISSUE THREAD

**Issue by Isabela-Sales** [Isabela-Sales/kraken-good-accessibility#1]
Hello Christian!

Here is my completed assignment.
Thank you!

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Well done! Only a small comment on how the aria-labels are written as the nav is supposed to go to the prev/next _chapter_ but _content_ also works - and at that point I'm being really picky.

I like the descriptive alt text for the image, and the voiceover rotor shows that things are easy to locate and make sense

I've added the grade to LTW 🙌

**Comment by Isabela-Sales** [comment]
Thank you for your feedback, @thatkidmadrid !

Just one question before closing the issue.
I added the following code because Markbot was requesting it, but I have no idea what is really doing on the page.
     header nav:last-of-type a:not(.current) :hover
Could you explain that please?

**Comment by thatkidmadrid** [comment]
Weird, I don't have that in my code... could you send me the full markbot screenshot so I have more context?

Essentially what that selector is doing:
- select the last `nav` that appears in any `header`
- in those `nav`s, select only links(`a`) that do not have the class `.current`
- style the `hover` state of those links(`a`)

From what I see in your code it's just setting the colour to white, but the icons are already white, so I'm not sure what markbot is complaining about

**Comment by Isabela-Sales** [comment]
Sure, this attached screenshot is what I see if I delete that line of code.
The colour was only my guess, Markbot didn't specify this.
But anyway, thanks for clarifying what the selector does.

<img width="513" alt="Screen Shot 2021-10-03 at 7 42 15 PM" src="https://user-images.githubusercontent.com/77288262/135898069-7dba4807-93b1-4dd1-9010-a3a3b83027db.png">
.
